
on:
  push:
    branches:
      - master

jobs:
  deploy_project:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: google-github-actions/auth@v1
        with:
          credentials_json: "${{ secrets.GCP_SERVICE_ACCOUNT_FILE }}"

      - uses: google-github-actions/setup-gcloud@v1

      - name: Docker auth
        run: gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

      - name: Build & Push Docker image
        run: |
          docker build -t us-central1-docker.pkg.dev/de-practice-469814/ci-cd-example/ci-cd-example:latest .
          docker push us-central1-docker.pkg.dev/de-practice-469814/ci-cd-example/ci-cd-example:latest

