
on:
  pull_request:
    branches:
      - master

jobs:
  build_project:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install requirements.txt
        run: pip install -r requirements.txt

      - name: Run code
        run: python main.py
